/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Uhuuy31
 */
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

public class tampilanAutisme extends javax.swing.JFrame {

    /**
     * Creates new form tampilanAutisme
     */
    autisme gui;
    autismeChat guiChat;
    DecimalFormat desimal = new DecimalFormat("0.000");

    public tampilanAutisme() {
        initComponents();
        gui = new autisme();
        guiChat = new autismeChat();
        //tampilKromosom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        atasTiga = new javax.swing.JRadioButton();
        bawahTiga = new javax.swing.JRadioButton();
        generasi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        populasi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        probcros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        probmutasi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pilihIndex = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup3.add(atasTiga);
        atasTiga.setText("Diatas 3 Tahun");
        atasTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atasTigaActionPerformed(evt);
            }
        });

        buttonGroup3.add(bawahTiga);
        bawahTiga.setText("Dibawah 3 Tahun");

        generasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generasiActionPerformed(evt);
            }
        });

        jLabel1.setText("Generasi");

        jLabel2.setText("Populasi");

        jLabel3.setText("Probabilitas Crossover");

        jLabel4.setText("Probabilitas Mutasi");

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane1.addTab("Kromosom", jScrollPane3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(620, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data", jPanel1);

        jLabel5.setText("Pilih Index");

        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(probcros)
                                    .addComponent(probmutasi)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(pilihIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(atasTiga)
                            .addComponent(bawahTiga))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(populasi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generasi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atasTiga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bawahTiga)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(populasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(probcros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(probmutasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pilihIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        atasTiga.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generasiActionPerformed
    public void tampilDataCARS(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("No");
        tabel.addColumn("Komsos");
        tabel.addColumn("Indera");
        tabel.addColumn("Perilaku");
        tabel.addColumn("P.info");
        tabel.addColumn("D.Pakar");
        tabel.addColumn("D.Sistem");
        jTable1.setModel(tabel);
        
        for (int i = 0; i < 20; i++) {
             tabel.addRow(new Object[]{
                 i+1, 
                 gui.inputTest[i][0],
                 gui.inputTest[i][1],
                 gui.inputTest[i][2],
                 gui.inputTest[i][3],
                 gui.targetTest[i],
                 gui.hasilS[i]});
        }
        
        tabel.addRow(new Object[] {
            "Total ",
            " ",
            " ",
            " ",
            " ",
            " ",
            gui.countAkurasi});
        
    }
    public void tampilKromosomCARS() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("No");
        tabel.addColumn("K1");
        tabel.addColumn("K2");
        tabel.addColumn("K3");
        tabel.addColumn("K4");
        tabel.addColumn("I1");
        tabel.addColumn("I2");
        tabel.addColumn("I3");
        tabel.addColumn("I4");
        tabel.addColumn("P1");
        tabel.addColumn("P2");
        tabel.addColumn("P3");
        tabel.addColumn("P4");
        tabel.addColumn("PI1");
        tabel.addColumn("PI2");
        tabel.addColumn("PI3");
        tabel.addColumn("PI4");
        tabel.addColumn("PO1");
        tabel.addColumn("PO2");
        tabel.addColumn("FITNESS");
        jTable3.setModel(tabel);

        int pop = Integer.parseInt(populasi.getText());
        for (int i = 0; i < pop; i++) {
            tabel.addRow(new Object[]{
                i + 1,
                desimal.format(gui.individu[i][0]),
                desimal.format(gui.individu[i][1]),
                desimal.format(gui.individu[i][2]),
                desimal.format(gui.individu[i][3]),
                desimal.format(gui.individu[i][4]),
                desimal.format(gui.individu[i][5]),
                desimal.format(gui.individu[i][6]),
                desimal.format(gui.individu[i][7]),
                desimal.format(gui.individu[i][8]),
                desimal.format(gui.individu[i][9]),
                desimal.format(gui.individu[i][10]),
                desimal.format(gui.individu[i][11]),
                desimal.format(gui.individu[i][12]),
                desimal.format(gui.individu[i][13]),
                desimal.format(gui.individu[i][14]),
                desimal.format(gui.individu[i][15]),
                desimal.format(gui.individu[i][16]),
                desimal.format(gui.individu[i][17]),
                gui.fitnessGabungan[i]
            });
        }
    }

    public void tampilKromosomCHAT() {
        DefaultTableModel tabel1 = new DefaultTableModel();
        tabel1.addColumn("No");
        tabel1.addColumn("Alo1");
        tabel1.addColumn("Alo2");
        tabel1.addColumn("P1");
        tabel1.addColumn("P2");
        tabel1.addColumn("Po1");
        tabel1.addColumn("Po2");
        tabel1.addColumn("FITNESS");
        jTable3.setModel(tabel1);

        int pop = Integer.parseInt(populasi.getText());
        for (int i = 0; i < pop; i++) {
            tabel1.addRow(new Object[]{
                i + 1,
                desimal.format(guiChat.individu[i][0]),
                desimal.format(guiChat.individu[i][1]),
                desimal.format(guiChat.individu[i][2]),
                desimal.format(guiChat.individu[i][3]),
                desimal.format(guiChat.individu[i][4]),
                desimal.format(guiChat.individu[i][5]),
                guiChat.fitnessGabungan[i]
            });
        }
    }
    public void tampilDataCHAT(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("No");
        tabel.addColumn("Alo Anamnesis");
        tabel.addColumn("Pengamatan");
        tabel.addColumn("D.Pakar");
        tabel.addColumn("D.Sistem");
        jTable1.setModel(tabel);
        
        for (int i = 0; i < 30; i++) {
             tabel.addRow(new Object[]{
                 i+1, 
                 guiChat.input[i][0],
                 guiChat.input[i][1],
                 guiChat.target[i],
                 guiChat.hasilS[i]});
        }
        
        tabel.addRow(new Object[] {
            "Total ",
            " ",
            " ",
            " ",
            guiChat.countAkurasi});
        
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a, b, c, d;
        a = generasi.getText();
        b = populasi.getText();
        c = probcros.getText();
        d = probmutasi.getText();

        int g = Integer.parseInt(a);
        int p = Integer.parseInt(b);
        double pc = Double.parseDouble(c);
        double pm = Double.parseDouble(d);

        if (atasTiga.isSelected()) {
            gui.input(g, p, pc, pm);
            gui.jalankan();
            tampilKromosomCARS();
            tampilDataCARS();
        } else {
            guiChat.input(g, p, pc, pm);
            guiChat.jalankan();
            tampilKromosomCHAT();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void atasTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atasTigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atasTigaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(pilihIndex.getText());
        if (atasTiga.isSelected()) {
            gui.jalankanData(x-1);
            tampilDataCARS();
        } else {
            guiChat.jalankanData(x-1);
            tampilDataCHAT();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

//    public void prosesAtasTiga(int banyakGenerasi, int popSize, double pm, double pc) {
//        a.jalankan(banyakGenerasi, popSize, pm, pc);
//    }
    autismeChat b = new autismeChat();

    public void prosesBawahTiga(int banyakGenerasi, int popSize, double pm, double pc) {
        //b.jalankan(banyakGenerasi, popSize, pm, pc);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilanAutisme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilanAutisme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilanAutisme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilanAutisme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilanAutisme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton atasTiga;
    private javax.swing.JRadioButton bawahTiga;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField generasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField pilihIndex;
    private javax.swing.JTextField populasi;
    private javax.swing.JTextField probcros;
    private javax.swing.JTextField probmutasi;
    // End of variables declaration//GEN-END:variables
}
